# Configuration file for pre-commit (https://pre-commit.com/).
# Please run `pre-commit run --all-files` when adding or changing entries.

repos:
  - repo: https://github.com/jorisroovers/gitlint
    rev: acc9d9de6369b76d22cb4167029d2035e8730b98 # frozen: v0.19.1
    hooks:
      - id: gitlint
      - id: gitlint-ci

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: fc260393cc4ec09f8fc0a5ba4437f481c8b55dc1 # frozen: v3.0.3
    hooks:
      - id: prettier
        stages: [commit]

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: ebdf1faf0ebf43b29c659da8741252c925e690c8 # frozen: 0.26.3
    hooks:
      - id: check-github-workflows
        name: Check Github workflows
        stages: [commit]

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: 3f77b826548d8dc2d26675f077361c92773b50a7 # frozen: v0.9.0
    hooks:
      - id: shellcheck
        stages: [commit]

  - repo: local
    hooks:
      - id: pathchk
        name: pathchk
        entry: pathchk
        args: [--portability]
        types: [file]
        exclude: ^([a-zA-Z0-9._][a-zA-Z0-9._-]+)(/[a-zA-Z0-9._][a-zA-Z0-9._-]+)*$ # https://lists.gnu.org/archive/html/coreutils/2023-01/msg00006.html
        language: system
        stages: [commit]

  - repo: meta
    hooks:
      - id: check-useless-excludes
        stages: [commit]
