name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04

    # Limit deploys to one at a time
    concurrency: deploy-${{ github.ref }}

    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v4.0.0
        with:
          fetch-depth: 0 # Enable checking Git history

      - name: Get Node.js version
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> "$GITHUB_ENV"

      - name: Build and test with Node.js ${{ env.NODE_VERSION }}
        uses: linz/action-typescript@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://npm.pkg.github.com'
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Get Python version
        run: echo "PYTHON_VERSION=$(cat .python-version)" >> "$GITHUB_ENV"

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4.7.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Lint files in non-${{ github.event.repository.default_branch }} branches
        run: pre-commit run --all-files --verbose
        if: github.ref != 'refs/heads/${{ github.event.repository.default_branch }}'

      - name: Check all commit messages in non-${{ github.event.repository.default_branch }} branches
        run: pre-commit run --hook-stage=manual --verbose
        if: github.ref != 'refs/heads/${{ github.event.repository.default_branch }}'

      - name: Configure AWS Credentials
        if: github.ref == 'refs/heads/master' && github.repository == 'linz/hydro-aws-infrastructure'
        uses: aws-actions/configure-aws-credentials@v4.0.0
        with:
          aws-region: ap-southeast-2
          role-to-assume: ${{ secrets.AWS_ROLE_PROD }}

      - name: Deploy
        if: github.ref == 'refs/heads/master' && github.repository == 'linz/hydro-aws-infrastructure'
        run: node run cdk deploy --require-approval=never hydro-aws-infrastructure-stack
