name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.6.0

      - name: Get Node.js version
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> "$GITHUB_ENV"

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3.8.1
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://npm.pkg.github.com/
          scope: '@linz'
          cache: 'yarn'

      - name: Install Node.js packages
        run: yarn
        env:
          NODE_AUTH_TOKEN: ${{ secrets.AUTH_TOKEN_GITHUB_PACKAGES }}

      - name: Build
        run: yarn run build

      - name: Lint
        run: yarn run lint

      - name: Check formatting
        run: git diff --exit-code

      - name: Test
        run: yarn run test

  build-nix-shell:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3.6.0

      - uses: cachix/install-nix-action@v22

      - uses: cachix/cachix-action@v12
        with:
          name: linz
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - run: nix-shell --pure --run 'yarn run test'
